name: blm2020
recipe: backdrop
config:
  webroot: web
  php: '7.0'
  via: apache

services:
  appserver:
    build:
      - cd $LANDO_MOUNT && composer install
      - composer global require laravel/envoy
  database:
    type: mariadb
    portforward: 6618
  cividatabase:
    type: mariadb
    portforward: 6619 
    creds:
      user: civi
      password: civi
      database: civi
  node-cli:
    type: node:6.10
    build:
      - cd $LANDO_MOUNT && npm install
    globals:
      gulp-cli: "latest"

# See: https://docs.lndo.io/config/tooling.html
tooling:
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli

