name: blm2020
recipe: backdrop
config:
  webroot: web
  php: '7.0'
  via: apache
  backdrush: 0.0.6
  xdebug: true
services:
  appserver:
    run:
      - composer global require laravel/envoy
  database:
    type: mariadb
    portforward: 6618
  cividatabase:
    type: mariadb
    portforward: 6619 
    creds:
      user: civi
      password: civi
      database: civi
  node-cli:
    type: node:6.10
    run:
      - cd $LANDO_MOUNT && npm install
    globals:
      gulp-cli: "latest"

# See: https://docs.lndo.io/config/tooling.html
tooling:
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli

